import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


async function CookiesComponent() {
  const allCookies = (await cookies()).getAll();

  return (
    <div style={{ padding: "2rem" }}>
      <p>Here are all the cookies:</p>
       <code>{JSON.stringify(allCookies, null, 2)}</code>
    </div>
 
  );
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          {children}
          <CookiesComponent />
        </main>
      </body>
    </html>
  );
}
